### ISSUE TITLE
creating simple movement w/ cyton_gamma_1500

### ISSUE THREAD

**Issue by mortimer92** [GertKanter/cyton_gamma_1500_description#2]
Hello there !

```
I don't know if I'm putting this right, but, I have used RViz and observed that
```

for each segment of the robot there are some coordinates indicating the position of each.
 Now... for my project I must be able to do a simple movement with the robotic arm and I was wondering 
if somehow there is a way to fetch those coordinates from a somewhere and maybe create a file of my own that
will give a specific position. If not, maybe some directions? because I'm using ROS and do not know where to
find materials.

**Comment by GertKanter** [comment]
This model is compatible with MoveIt! motion planning package (http://moveit.ros.org/). I have successfully used MoveIt! to plan poses and execute them on the real manipulators with this model.

Unfortunately, I am unable to share any code for it at the moment. After a few of months, I might be able to share the full code to get a standalone Cyton Gamma 1500 working with motion planning and execution (if nobody has shared a working solution). This might not happen though as this work has no real overlap with my current work and I am overburdened with other work.

Taking all that into consideration, you should probably try to get it to work on your own. This model can be used as the input for creating the MoveIt config (there is a nice setup assistant that helps a lot). Other than that, if you have problems, you should ask the MoveIt mailing list, because there are close to 600 members in there. There is also a lot of previous posts there that you can browse. You can find the information at MoveIt! support page. Good luck!
